name: postman-newman
on: [push, pull_request]
jobs:
  run-newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm i -g newman newman-reporter-htmlextra
      - run: |
          mkdir -p reports
          newman run collections/ecommerce.postman_collection.json \
            -e envs/dev.postman_environment.json \
            -r htmlextra --reporter-htmlextra-export reports/report.html
      - uses: actions/upload-artifact@v4
        with:
          name: newman-report
          path: reports/report.html
